### ISSUE TITLE
Collaboration with Letuscrack

### ISSUE THREAD

**Issue by hemanthtejadasari** [HEPHZIBAI/skillrack-daily-challange#1]
Dear Hephzibai,

My sincere apologies for reaching out through a GitHub issue, but unfortunately, we encountered challenges in locating your social media handle.

I hope you are doing well. My name is Hemanth, and I am a 2021 graduate of R.M.D. Engineering College representing Letuscrack (code.letuscrack.com).

We are looking for dedicated individuals like you who can contribute to students' educational journeys by producing insightful articles on our platforms. Your experience can make a major difference, and we would be delighted to have you on board.

We currently rely largely on Google Ads, but we are willing to explore additional opportunities. As a mark of gratitude for your work, we are willing to share 100% of the revenue generated by your articles. In addition, we provide perks such as certification to honour and recognise your dedication.

We truly hope you would consider this opportunity to join us in our aim of empowering and assisting students through great information. We gladly await your response.

Best Regards,
Hemanth, 
Founder of Letuscrack.

**Comment by HEPHZIBAI** [comment]
Hi Hemanth,

Thank you for reaching out and for considering me to join Letuscrack. I am honored by the opportunity to contribute to students' educational journeys and share my insights through your platform.

I am excited to accept your invitation and look forward to being a part of Letuscrack. I believe in the power of education and am eager to contribute to your mission of empowering and assisting students with valuable information.

Please provide me with further details regarding the onboarding process, guidelines for article submissions, and any other necessary information. I am ready to contribute and be a part of the Letuscrack community.

Best Regards,
Hephzibai

**Comment by hemanthtejadasari** [comment]
Hi Hephzibai,

Appreciate your interest in becoming a part of our community. kindly reach out to us through Instagram or LinkedIn.

Letuscrack - https://instagram.com/letuscrack
Personal - https://instagram.com/hemanthuuuuu

Best regards,
Hemanth.
